### ISSUE TITLE
demo code doesn't work

### ISSUE THREAD

**Issue by sandover** [kirbysayshi/pocket-physics#3]
- The 2d example mentions 'point1', should be 'point'
- The 3d example produces strange results.  point1 and point2 don't have z values -- should they? 
If I add z: fields, then the behavior I see is point2 moving away and point1 not moving.  This doesn't seem to obey the constraint.    But I'm just encountering the library for the first time so not sure.

**Comment by kirbysayshi** [comment]
Thanks for reporting that the examples were off. I'd forgotten to update them. Better examples (that work) can be found in [test3d.js](./test3d.js). I also made a requirebin live example for you: http://requirebin.com/?gist=bafff38038be6bb60a3e

It's not optimized (for example, you shouldn't trigger physics calcs based on requestAnimationFrame, and it's touching the DOM to grab width/height for clearing the canvas).

Hope this helps, and if you find more bugs, submit a PR!

**Comment by kirbysayshi** [comment]
Going to close this, but reopen if you're still having issues.

**Comment by sandover** [comment]
cool, thanks!
